### PR TITLE
issue fix, theme color change -> 'android-js/androidjs/issues/160'

### PR DESCRIPTION
**Pull request by dydgns2017**
error fix for theme color change

i was test that it works good

issue log => android-js/androidjs/issues/160

### CODE REVIEW

**Comment by dydgns2017** [comment]
@Chhekur are u not enough time to review this request?

**Comment by dydgns2017** [comment]
https://github.com/android-js/androidjs-builder/pull/45/commits/39dc54ff8bfa4cc5196f4cac4a5e27ed53586b8b -> this [link](https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df) for reference to solved

**Comment by Chhekur** [comment]
@dydgns2017 hey, I'll review it by today. 
Sorry for the delay!

**Comment by dydgns2017** [comment]
@Chhekur Thank u :D

**Review by Chhekur — APPROVED** [review]
LGTM

**Pull request merged**
